apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-react
  template:
    metadata:
      labels:
        app: todo-list-react
    spec:
      containers:
      - name: todo-list-react
        image: natiiyov/todo-list:testing-1.0
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE
          valueFrom:
            secretKeyRef:
              name: todo-list-react-secrets
              key: REACT_APP_API_BASE
