apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-list-mongo-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs/volumes/todo-list-mongo-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-list-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

