apiVersion: v1
kind: Service
metadata:
  name: todo-list-mongo-service
spec:
  selector:
    app: todo-list-mongo-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
